---
name: reviewdog
on:  # yamllint disable-line rule:truthy
  push:

jobs:

  yamllint:
    name: runner / yamllint
    if: |
      (github.actor!= 'dependabot[bot]') &&
      (contains(github.head_ref, 'dependabot/github_actions/') == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.6.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
